version: "3.8"

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5173"
    volumes:
      - ./src:/usr/etc/sveltekit/src
      - ./static:/usr/etc/sveltekit/static
      - ./vite.config.ts:/usr/etc/sveltekit/vite.config.ts
      - ./tsconfig.json:/usr/etc/sveltekit/tsconfig.json
      - ./svelte.config.js:/usr/etc/sveltekit/svelte.config.js
      - ./tailwind.config.js:/usr/etc/sveltekit/tailwind.config.js
      - ./postcss.config.js:/usr/etc/sveltekit/postcss.config.js
    command: npm run dev
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/lokate_dev
      - PORT=5173
      - HOST=0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lokate_dev
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
